project:
  type: book
  resources:
    - img/slides/*
    - img/mixed/*
  output-dir: docs
  render:
    - index.qmd
    - intro.qmd
    - Assignment1.qmd
    - Assignment1Q.qmd
    - Readings1.qmd
    - assignment2_intro.qmd
    - assignment2.qmd
    - Readings2.qmd
    - linearmodels.qmd
    - assignment3.qmd
    - assignment4.qmd
    - assignment5.qmd
    - overdispersion.qmd
    - mixed.qmd
    - mixedmfish.qmd
    - glmmmodelsanswers.qmd
    - gamassignment.qmd
    - assignment_MV.qmd
    - bayesian.qmd
    - references.qmd
    - Slideshows.qmd
    - Installation_instructions.qmd
    - Datawrangling.qmd
    - r-shiny_example.qmd
    - FunctionsinR.qmd


book:
  title: "FWF 610 "
  subtitle: "Data Modeling and Visualization Using R"
  author: "Alejandro Molina Moctezuma"
  date: "6/6/2025"
  page-footer: "Alejandro Molina-Moctezuma, 2025"
  downloads: [pdf, epub]
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters:
        - Assignment1.qmd
        - Assignment1Q.qmd
        - Readings1.qmd
    - part: assignment2_intro.qmd
      chapters:
        - assignment2.qmd
        - Readings2.qmd
    - part: linearmodels.qmd
      chapters:
        - assignment3.qmd
    - assignment4.qmd
    - assignment5.qmd
    - overdispersion.qmd
    - part: mixed.qmd
      chapters:
        - mixedmfish.qmd
        - glmmmodelsanswers.qmd
    - gamassignment.qmd
    - assignment_MV.qmd
    - Bayesian.qmd
    - references.qmd
    - Slideshows.qmd
  appendices:
    - Installation_instructions.qmd
    - Datawrangling.qmd
    - r-shiny_example.qmd
    - FunctionsinR.qmd
  navbar:
    search: true
    background: light
    left:
      - text: "Home"
        href: index.qmd
      - text: "Fisheries Research Group website"
        href: https://moctezumaii.github.io/labwebsitetest/


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt


number-sections: true

editor: visual

