<!DOCTYPE html>
<html lang="en"><head>
<script src="GLM_Poisson2_files/libs/clipboard/clipboard.min.js"></script>
<script src="GLM_Poisson2_files/libs/quarto-html/tabby.min.js"></script>
<script src="GLM_Poisson2_files/libs/quarto-html/popper.min.js"></script>
<script src="GLM_Poisson2_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="GLM_Poisson2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="GLM_Poisson2_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="GLM_Poisson2_files/libs/quarto-html/quarto-syntax-highlighting-29e2c20b02301cfff04dc8050bf30c7e.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.37">

  <title>Mixed Effects Models</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="GLM_Poisson2_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="GLM_Poisson2_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="GLM_Poisson2_files/libs/revealjs/dist/theme/quarto-bbe7401fe57d4b791b917637bb662036.css">
  <link href="GLM_Poisson2_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="GLM_Poisson2_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="GLM_Poisson2_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="GLM_Poisson2_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="GLM_Poisson2_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="GLM_Poisson2_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Mixed Effects Models</h1>

<div class="quarto-title-authors">
</div>

</section>
<section id="this-lecture" class="slide level2">
<h2>This lecture</h2>
<p>Review of linear models</p>
<p>Assumptions of glm’s</p>
<p>Overdispersion</p>
</section>
<section id="how-to-interpret-glms-outputs" class="slide level2">
<h2>How to interpret GLM’s outputs?</h2>
<ul>
<li class="fragment">Let’s remember that linear models, and glm’s have a “linear” deterministic component</li>
</ul>

<img data-src="GLM_Poisson2_files/figure-revealjs/unnamed-chunk-1-1.png" width="960" class="r-stretch"></section>
<section id="how-to-interpret-glms-outputs-1" class="slide level2">
<h2>How to interpret GLM’s outputs?</h2>
<ul>
<li class="fragment"><p>Let’s remember that linear models, and glm’s have a “linear” deterministic component</p></li>
<li class="fragment"><p>In linear models: <span class="math inline">\(\mu_i = \beta_0 + \beta_1x_{1,i} ...\)</span> (which means, the expected value of y )</p></li>
<li class="fragment"><p>In generalized linear models: <span class="math inline">\(f(\mu_i) = \beta_0 + \beta_1x_{1,i} ...\)</span> (which means, a function of the expected value of y)</p></li>
</ul>
</section>
<section id="the-deterministic-component-is-linear" class="slide level2">
<h2>The deterministic component is linear</h2>
<p>Which is a good thing! Each linear has two components!</p>
<ul>
<li class="fragment"><p>A slope</p></li>
<li class="fragment"><p>An intercept</p></li>
</ul>
</section>
<section id="the-deterministic-component-is-linear-1" class="slide level2">
<h2>The deterministic component is linear</h2>
<p>Which is a good thing! Each linear (not polynomial… let’s forget about that for a little while) has two components!</p>
<div>
<ul>
<li><p>A slope</p></li>
<li><p>An intercept</p></li>
</ul>
</div>
<p><span class="math display">\[
y = mx + b
\]</span></p>
</section>
<section id="the-deterministic-component-is-linear-2" class="slide level2">
<h2>The deterministic component is linear</h2>
<p>Which is a good thing! Each linear (not polynomial… let’s forget about that for a little while) has two components!</p>
<div>
<ul>
<li><p>A slope</p></li>
<li><p>An intercept</p></li>
</ul>
</div>
<p><span class="math display">\[
y = mx + b = b + mx
\]</span></p>
<p>is not any different than:</p>
<p><span class="math display">\[
\begin{align}
\mu_i &amp; = \beta_0 + \beta_1x_{1,i} \\
y_i &amp; \sim N(mean = \mu_i, var=\sigma^2)
\end{align}
\]</span></p>
</section>
<section id="lets-remember-what-a-slope-and-an-intercept-is" class="slide level2">
<h2>Let’s remember what a slope and an intercept is</h2>

<img data-src="GLM_Poisson2_files/figure-revealjs/unnamed-chunk-2-1.png" width="960" class="r-stretch"></section>
<section id="lets-remember-what-a-slope-and-an-intercept-is-1" class="slide level2">
<h2>Let’s remember what a slope and an intercept is</h2>

<img data-src="GLM_Poisson2_files/figure-revealjs/unnamed-chunk-3-1.png" width="960" class="r-stretch"></section>
<section id="lets-remember-what-a-slope-and-an-intercept-is-2" class="slide level2">
<h2>Let’s remember what a slope and an intercept is</h2>

<img data-src="GLM_Poisson2_files/figure-revealjs/unnamed-chunk-4-1.png" width="960" class="r-stretch"></section>
<section id="lets-remember-what-a-slope-and-an-intercept-is-3" class="slide level2">
<h2>Let’s remember what a slope and an intercept is</h2>

<img data-src="GLM_Poisson2_files/figure-revealjs/unnamed-chunk-5-1.png" width="960" class="r-stretch"><ul>
<li class="fragment"><p>Slope: For very change in x of 1, y changes 1.5. Intercept: 2</p></li>
<li class="fragment"><p>So, if x = 5, then y = 2 + 1.5(5) = 9.5</p></li>
</ul>
</section>
<section id="so-what-about-linear-models" class="slide level2">
<h2>So, what about linear models?</h2>
<p>Each line in a linear model simply has: 1 slope and 1 intercept.</p>

<img data-src="GLM_Poisson2_files/figure-revealjs/unnamed-chunk-6-1.png" width="960" class="r-stretch"></section>
<section id="so-what-about-linear-models-1" class="slide level2">
<h2>So, what about linear models?</h2>
<p>What is the slope? what is the intercept?</p>

<img data-src="GLM_Poisson2_files/figure-revealjs/unnamed-chunk-7-1.png" width="960" class="r-stretch"></section>
<section id="so-what-about-linear-models-2" class="slide level2">
<h2>So, what about linear models?</h2>
<p><span class="math display">\[
\begin{split}
y_i &amp; \sim \beta_0 + \beta_1x_i + \epsilon_i \\
\text{where } \epsilon &amp; \sim normal(0,\sigma)
\end{split}
\]</span> Or, in this specific case:</p>
<p><span class="math display">\[
Reproductive \ effort_i \sim \beta_0 + \beta_1Food \ availability_i + \epsilon_i \\
\]</span></p>
</section>
<section id="intercept-and-slope-in-linear-models" class="slide level2">
<h2>Intercept and Slope in Linear Models</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ReproductiveEffort ~ Foodavailability, data = foodav)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.37653 -0.25549 -0.04903  0.23662  0.45750 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       0.89490    0.07262   12.32   &lt;2e-16 ***
Foodavailability  1.19387    0.01590   75.08   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2652 on 61 degrees of freedom
Multiple R-squared:  0.9893,    Adjusted R-squared:  0.9891 
F-statistic:  5636 on 1 and 61 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li class="fragment"><p>Intercept: 0.895</p></li>
<li class="fragment"><p>Slope: 1.194</p></li>
</ul>
<p><span class="math display">\[
\begin{split}
y_i &amp; \sim \beta_0 + \beta_1x_i + \epsilon_i \\
\text{where } \epsilon &amp; \sim normal(0,\sigma)
\end{split}
\]</span></p>
</section>
<section id="results" class="slide level2">
<h2>Results</h2>
<table class="caption-top">
<colgroup>
<col style="width: 30%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>t-value (test)</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept <span class="math inline">\(\beta_0\)</span></td>
<td>0.895</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Slope <span class="math inline">\(\beta_1\)</span></td>
<td>1.194</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
\begin{split}
y_i &amp; \sim \beta_0 + \beta_1x_i + \epsilon_i \\
\text{where } \epsilon &amp; \sim normal(0,\sigma)
\end{split}
\]</span></p>
</section>
<section id="results-1" class="slide level2">
<h2>Results</h2>
<table class="caption-top">
<colgroup>
<col style="width: 30%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>t-value (test)</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept <span class="math inline">\(\beta_0\)</span></td>
<td>0.895</td>
<td>0.072</td>
<td>12.32</td>
<td>&lt;0.0001</td>
</tr>
<tr class="even">
<td>Slope <span class="math inline">\(\beta_1\)</span></td>
<td>1.194</td>
<td>0.0159</td>
<td>75.08</td>
<td>&lt;0.0001</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[ \begin{split} y_i &amp; \sim \beta_0 + \beta_1x_i + \epsilon_i \\ \text{where } \epsilon &amp; \sim normal(0,\sigma) \end{split} \]</span></p>
<ul>
<li class="fragment"><p>Test:</p></li>
<li class="fragment"><p>Ho: Coefficient == 0</p></li>
<li class="fragment"><p>Ha Coefficient != 0</p></li>
</ul>
</section>
<section id="how-about-this-one" class="slide level2">
<h2>How about this one:</h2>

<img data-src="GLM_Poisson2_files/figure-revealjs/unnamed-chunk-9-1.png" width="960" class="r-stretch"></section>
<section id="how-about-this-one-1" class="slide level2">
<h2>How about this one:</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = FC ~ IC + Dose, data = drugz)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.2610 -0.6360  0.0000  0.6514  2.2876 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.51804    0.38892   1.332   0.1849    
IC           0.93384    0.05647  16.537   &lt;2e-16 ***
Dosedose1   -0.44007    0.20011  -2.199   0.0294 *  
Dosedose2   -2.09915    0.20162 -10.412   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9893 on 146 degrees of freedom
Multiple R-squared:  0.7636,    Adjusted R-squared:  0.7588 
F-statistic: 157.2 on 3 and 146 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li class="fragment">Additive model means only one slope is estimated!</li>
</ul>
</section>
<section id="back-to-the-plot" class="slide level2">
<h2>Back to the plot</h2>

<img data-src="GLM_Poisson2_files/figure-revealjs/unnamed-chunk-11-1.png" width="960" class="r-stretch"><ul>
<li class="fragment"><p>Parallel lines</p></li>
<li class="fragment"><p>1 slope, 3 intercepts</p></li>
<li class="fragment"><p>Each line: <span class="math inline">\(y = mx + b\)</span></p></li>
</ul>
</section>
<section id="finding-values" class="slide level2">
<h2>Finding values</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = FC ~ IC + Dose, data = drugz)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.2610 -0.6360  0.0000  0.6514  2.2876 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.51804    0.38892   1.332   0.1849    
IC           0.93384    0.05647  16.537   &lt;2e-16 ***
Dosedose1   -0.44007    0.20011  -2.199   0.0294 *  
Dosedose2   -2.09915    0.20162 -10.412   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9893 on 146 degrees of freedom
Multiple R-squared:  0.7636,    Adjusted R-squared:  0.7588 
F-statistic: 157.2 on 3 and 146 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><span class="math display">\[
\begin{align}
\beta_0 &amp; = 0.51 \ \text{intercept for control} \\
\beta_1 &amp; = 0.93 \ \text{slope} \\
\beta_2 &amp; = -0.44 \ \text{Difference in intercept between control and dose 1} \\
\beta_2 &amp; = -2.099 \ \text{Difference in intercept between control and dose 2} \\
\end{align}
\]</span></p>
<p><span class="math display">\[
y_i \sim \beta_0 + \beta_1x_{1,i}  + \beta_2x_{2,i} +  \beta_3x_{3,i} + \epsilon_i \\
\]</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Site</th>
<th>Value of <span class="math inline">\(x_2\)</span></th>
<th>Value of <span class="math inline">\(x_3\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Control</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Dose 1</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Dose 2</td>
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>
</section>
<section id="finding-values-1" class="slide level2">
<h2>Finding values</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = FC ~ IC + Dose, data = drugz)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.2610 -0.6360  0.0000  0.6514  2.2876 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.51804    0.38892   1.332   0.1849    
IC           0.93384    0.05647  16.537   &lt;2e-16 ***
Dosedose1   -0.44007    0.20011  -2.199   0.0294 *  
Dosedose2   -2.09915    0.20162 -10.412   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9893 on 146 degrees of freedom
Multiple R-squared:  0.7636,    Adjusted R-squared:  0.7588 
F-statistic: 157.2 on 3 and 146 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<table class="caption-top">
<thead>
<tr class="header">
<th>Measurement</th>
<th>Intercept</th>
<th>Slope</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Control</td>
<td>0.51</td>
<td>0.93</td>
</tr>
<tr class="even">
<td>Dose 1</td>
<td>0.51 - 0.44</td>
<td>0.93</td>
</tr>
<tr class="odd">
<td>Dose 2</td>
<td>0.51 -2.099</td>
<td>0.93</td>
</tr>
</tbody>
</table>
</section>
<section id="statistical-inference" class="slide level2">
<h2>Statistical inference</h2>
<p><code>anova</code></p>
<p><code>emmeans</code></p>
<p><code>contrast</code></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: FC
           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
IC          1 342.36  342.36 349.825 &lt; 2.2e-16 ***
Dose        2 119.30   59.65  60.949 &lt; 2.2e-16 ***
Residuals 146 142.89    0.98                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast        estimate    SE  df t.ratio p.value
 control - dose1     0.44 0.200 146   2.199  0.0747
 control - dose2     2.10 0.202 146  10.412  &lt;.0001
 dose1 - dose2       1.66 0.198 146   8.377  &lt;.0001

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
</section>
<section id="statistical-inference-1" class="slide level2">
<h2>statistical inference</h2>
<p><code>anova</code> compares variance. Is the variance between groups higher than within groups?</p>

<img data-src="../img/slides/inference1.png" class="r-stretch"></section>
<section id="interactive" class="slide level2">
<h2>Interactive</h2>

<img data-src="GLM_Poisson2_files/figure-revealjs/unnamed-chunk-15-1.png" width="960" class="r-stretch"><ul>
<li class="fragment">Each line has its own slope and its own intercept</li>
</ul>
</section>
<section id="interactive-1" class="slide level2">
<h2>Interactive</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = FC ~ IC * Dose, data = drugz)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.3167 -0.6262 -0.0031  0.6443  2.1836 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   0.38733    0.59401   0.652   0.5154    
IC            0.95418    0.08981  10.624   &lt;2e-16 ***
Dosedose1     0.07353    0.85237   0.086   0.9314    
Dosedose2    -2.21858    0.86308  -2.571   0.0112 *  
IC:Dosedose1 -0.08529    0.13509  -0.631   0.5288    
IC:Dosedose2  0.02324    0.13917   0.167   0.8676    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9939 on 144 degrees of freedom
Multiple R-squared:  0.7647,    Adjusted R-squared:  0.7565 
F-statistic: 93.59 on 5 and 144 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><span class="math display">\[
\begin{align}
\beta_0 &amp; = 0.38 \ \text{intercept for control} \\
\beta_1 &amp; = 0.954 \ \text{slope for control} \\
\beta_2 &amp; = -0.073 \ \text{Difference in intercept between control and dose 1} \\
\beta_3 &amp; = -2.24 \ \text{Difference in intercept between control and dose 2} \\
\beta_4 &amp; = -0.085 \ \text{Difference in slope between control and dose 1} \\
\beta_5 &amp; = 0.023 \ \text{Difference in slope between control and dose 2} \\
\end{align}
\]</span></p>
<table class="caption-top">
<colgroup>
<col style="width: 12%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Site</th>
<th>Value of <span class="math inline">\(x_2\)</span></th>
<th>Value of <span class="math inline">\(x_3\)</span></th>
<th>Value of <span class="math inline">\(x_4\)</span></th>
<th>Value of <span class="math inline">\(x_5\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Control</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Dose 1</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Dose 2</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>
</section>
<section id="doing-inference-of-interactions" class="slide level2">
<h2>Doing inference of interactions</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: FC
           Df Sum Sq Mean Sq  F value Pr(&gt;F)    
IC          1 342.36  342.36 346.5514 &lt;2e-16 ***
Dose        2 119.30   59.65  60.3790 &lt;2e-16 ***
IC:Dose     2   0.63    0.31   0.3168  0.729    
Residuals 144 142.26    0.99                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>NOTE: Results may be misleading due to involvement in interactions</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast        estimate    SE  df t.ratio p.value
 control - dose1     0.44 0.202 144   2.173  0.0794
 control - dose2     2.08 0.204 144  10.175  &lt;.0001
 dose1 - dose2       1.64 0.201 144   8.136  &lt;.0001

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
</section>
<section id="interactions" class="slide level2">
<h2>Interactions</h2>

<img data-src="GLM_Poisson2_files/figure-revealjs/unnamed-chunk-18-1.png" width="960" class="r-stretch"></section>
<section id="finding-values-predictions" class="slide level2 scrollable">
<h2>Finding values (predictions)</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Assignment question 1 📝</strong></p>
</div>
<div class="callout-content">
<p>Look at the summary. And before continuing make sure you understand it. If you don’t, now is the time to raise your hand.</p>
<p>You need to calculate the expected probability (we’ll call this <span class="math inline">\(\pi\)</span>) of an individual being infected for each of the following two cases:</p>
<ol type="1">
<li class="fragment">An individual of length 50 from Area 1, in 1999</li>
<li class="fragment">An individual of length 50 from Area 3, in 2001</li>
</ol>
</div>
</div>
</div>
</section>
<section id="glm" class="slide level2">
<h2>GLM</h2>

<img data-src="GLM_Poisson2_files/figure-revealjs/unnamed-chunk-19-1.png" width="960" class="r-stretch"></section>
<section id="model" class="slide level2">
<h2>Model</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Prevalence ~ Length + Year + Area, family = binomial(link = "logit"), 
    data = cod)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -0.465947   0.269333  -1.730 0.083629 .  
Length       0.009654   0.004468   2.161 0.030705 *  
Year2000     0.566536   0.169715   3.338 0.000843 ***
Year2001    -0.680315   0.140175  -4.853 1.21e-06 ***
Area2       -0.626192   0.186617  -3.355 0.000792 ***
Area3       -0.510470   0.163396  -3.124 0.001783 ** 
Area4        1.233878   0.184652   6.682 2.35e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1727.8  on 1247  degrees of freedom
Residual deviance: 1537.6  on 1241  degrees of freedom
  (6 observations deleted due to missingness)
AIC: 1551.6

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>These are all from a linear model. Need to transform them to get the real value in probabilistic scale</p>
<p>Additive! One slope</p>
</section>
<section id="how-to-estimate-the-values" class="slide level2">
<h2>How to estimate the values?</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Prevalence ~ Length + Year + Area, family = binomial(link = "logit"), 
    data = cod)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -0.465947   0.269333  -1.730 0.083629 .  
Length       0.009654   0.004468   2.161 0.030705 *  
Year2000     0.566536   0.169715   3.338 0.000843 ***
Year2001    -0.680315   0.140175  -4.853 1.21e-06 ***
Area2       -0.626192   0.186617  -3.355 0.000792 ***
Area3       -0.510470   0.163396  -3.124 0.001783 ** 
Area4        1.233878   0.184652   6.682 2.35e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1727.8  on 1247  degrees of freedom
Residual deviance: 1537.6  on 1241  degrees of freedom
  (6 observations deleted due to missingness)
AIC: 1551.6

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p><span class="math display">\[
logistic(\pi_i)  = \beta_0 + \beta_1 x_{1,i}+ \beta_2 x_{2,i} + \beta_3 x_{3,i}+ \beta_4 x_{4,i} + \beta_5 x_{5,i} + \beta_6 x_{6,i}
\]</span></p>
<p>Site</p>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Value of <span class="math inline">\(x_2\)</span></th>
<th>Value of <span class="math inline">\(x_3\)</span></th>
<th>Value of <span class="math inline">\(x_4\)</span></th>
<th>Value of <span class="math inline">\(x_5\)</span></th>
<th>Value of <span class="math inline">\(x_6\)</span></th>
<th>Value of <span class="math inline">\(x_7\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>2000</td>
<td>2001</td>
<td>Area 1</td>
<td>Area 2</td>
<td>Area 3</td>
<td>Area 4</td>
</tr>
<tr class="even">
<td>Area-1 1999</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Area-1 2000</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Area-1 2001</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Area-2 1999</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Area-2 2000</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Area-2 2001</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Area 3- 1999</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Area 3 -2000</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="even">
<td>Area 3 - 2001</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Area 4 - 1999</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td>Area 4 - 2000</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Area 4 2001</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Area 1 -1999</p>
<p>Area 3 2001</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="logistic-regression-assumptions" class="slide level2">
<h2>Logistic regression assumptions</h2>
<ul>
<li class="fragment"><p>Binomial distribution</p></li>
<li class="fragment"><p>Binary data (1, 0)</p></li>
</ul>
</section>
<section id="poisson-assumptions" class="slide level2">
<h2>Poisson assumptions</h2>
<ul>
<li class="fragment"><p>We have talked about count-data</p></li>
<li class="fragment"><p>While we usually think Poisson, it has an important assumption: <span class="math inline">\(Var(y_i) = \lambda\_i\)</span></p></li>
</ul>

<img data-src="../img/slides/pois.png" class="r-stretch"></section>
<section id="how-to-check-for-overdispersion" class="slide level2">
<h2>How to check for overdispersion?</h2>
<p>Package: performance</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href=""></a> performance<span class="sc">::</span><span class="fu">check_overdispersion</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="what-to-do-when-there-is-overdispersion" class="slide level2">
<h2>What to do when there is overdispersion?</h2>
<p><strong>I have never encountered non-overdispersed count data!</strong></p>
<p>So, what to do?</p>
<ul>
<li class="fragment"><p>Add more covariates</p></li>
<li class="fragment"><p>Make a mixed effects model</p></li>
<li class="fragment"><p>Zero inflated models!</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href=""></a>performance<span class="sc">::</span><span class="fu">check_zeroinflation</span>(fit.pr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="what-to-do-when-there-is-overdispersion-1" class="slide level2">
<h2>What to do when there is overdispersion?</h2>
<p>If we suspect zero inflation, we have several options for zero inflated models</p>
<ul>
<li class="fragment"><p>Negative binomial regression</p></li>
<li class="fragment"><p>Hurdle models</p></li>
<li class="fragment"><p>Zero-inflated mixture model (mixed-effects)</p></li>
</ul>
</section>
<section id="glms-other-assumptions" class="slide level2">
<h2>GLM’s other assumptions</h2>
<ul>
<li class="fragment"><p>Data is independently distributed</p></li>
<li class="fragment"><p>Error is independent</p></li>
</ul>
</section>
<section id="question-1" class="slide level2">
<h2>Question 1</h2>
<p>Interested in the concentration of mercury in Lake Michigan</p>

<img data-src="../img/slides/michigan.png" class="r-stretch"><ul>
<li class="fragment"><p>We use code to randomly select 4 sites</p></li>
<li class="fragment"><p>At each site we set up a net</p></li>
<li class="fragment"><p>Return later and test Hg concentration of each fish</p></li>
</ul>
</section>
<section id="question-1-1" class="slide level2">
<h2>Question 1:</h2>
<ul>
<li class="fragment"><p>What is the experimental unit?</p></li>
<li class="fragment"><p>What is the response variable?</p></li>
<li class="fragment"><p>Where is sampling coming from or being introduced?</p></li>
<li class="fragment"><div>
<p><img data-src="../img/slides/fish.png"></p>
</div></li>
<li class="fragment"><p>What do we care about?</p></li>
</ul>
</section>
<section id="question-2" class="slide level2">
<h2>Question 2:</h2>
<ul>
<li class="fragment"><p>We are testing infection prevalence in turkeys 🦃</p></li>
<li class="fragment"><p>We trap multiple individuals from a flock, and test them all 🦃</p></li>
<li class="fragment"><p>We do this for multiple flocks</p></li>
<li class="fragment"><p>What is introducing variance?</p></li>
</ul>
</section>
<section id="question-3" class="slide level2">
<h2>Question 3</h2>
<ul>
<li class="fragment"><p>We are testing the effects of a new drug on mice</p></li>
<li class="fragment"><p>You have 100 🐁. And three groups: control, dose 1 and dose 2</p></li>
<li class="fragment"><p>You measure their heartbeat pre-trial, 5 weeks post trial, and 10 weeks post trial</p></li>
<li class="fragment"><p>Do we care about individual 🐭 or the general effect of the drug?</p></li>
</ul>
</section>
<section id="question-4" class="slide level2">
<h2>Question 4</h2>
<ul>
<li class="fragment"><p>Government is studying how quickly people return to work after receiving unemployment benefits at a national level based on their educational level</p></li>
<li class="fragment"><p>Each observation is an individual</p></li>
<li class="fragment"><p>Response variables are duartion of benefit, and explanatory variables are education, and industry</p></li>
<li class="fragment"><p>You randomly select 25 regional offices to obtain the data</p></li>
<li class="fragment"><p>We want to know national levels, but do regional differences matter?</p></li>
</ul>
</section>
<section id="research-questions" class="slide level2 scrollable">
<h2>Research Questions</h2>
<ol type="1">
<li class="fragment">Fish and Hg. <strong>Research question</strong>: Should we limit consumption of fish over a certain size</li>
<li class="fragment">Infection prevalence in turkeys: <strong>Research question</strong>: You are estimating the probability of an individual being infected to be used as a section on a demographic model?</li>
<li class="fragment">Mice. <strong>Research question</strong>:Is the drug affecting the mice heart rate?</li>
<li class="fragment">People <strong>Research question</strong>: How does educational level affect unemployment time?</li>
</ol>
</section>
<section id="experiments" class="slide level2">
<h2>Experiments : 🎣 🦃 🐁🧑‍🏭</h2>
<p>For one experiment answer:</p>
<ul>
<li class="fragment"><p>How would you analyze the data</p></li>
<li class="fragment"><p>Are they breaking any assumptions???</p></li>
<li class="fragment"><p>What is the individual unit, and what is the experimental unit</p></li>
<li class="fragment"><p>What is the response variable</p></li>
<li class="fragment"><p>Where is the variance coming from?</p></li>
</ul>
</section>
<section id="example-1" class="slide level2">
<h2>Example 1:</h2>
<p>In the first example, we are looking at the relationship between size and Hg concentration, in order to know whether to publish a consumption advisory for fish over a certain size. So, far, we have looked at examples in which our sampling is “random”</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      size        Hg ind
1 41.99086 1.3827550   1
2 33.89565 1.0172009   2
3 51.96077 1.5652670   3
4 20.23337 0.7227433   4
5 21.82249 0.8296023   5
6 21.12350 0.8224048   6</code></pre>
</div>
</div>
<ul>
<li class="fragment"><p>Could we simply look at it as</p></li>
<li class="fragment"><p><span class="math display">\[
Hg_i \sim \beta_0 + \beta_1 + \epsilon
\]</span></p></li>
</ul>
</section>
<section id="example-1-1" class="slide level2">
<h2>Example 1:</h2>
<p>But now the data looks like this:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       size        Hg region ind
1  41.99086 1.3827550      A   1
2  33.89565 1.0172009      A   2
3  51.96077 1.5652670      A   3
25 40.18645 1.4688691      B  25
26 37.12595 1.4055383      B  26
27 20.46721 1.0708612      B  27
56 49.80884 1.1882948      C  56
57 42.40157 0.9499704      C  57
80 56.51251 1.9176455      D  80
NA       NA        NA   &lt;NA&gt;  NA</code></pre>
</div>
</div>
<p>How do we analyze it?</p>
</section>
<section id="so-far-we-have-looked-at-linear-models-or-glms" class="slide level2">
<h2>So far we have looked at linear models (or glms)</h2>
<ul>
<li class="fragment"><p><span class="math display">\[
\underbrace{E[y_i]}_{\text{expected value}} = \underbrace{\beta_0 + \beta_1x_{1,i} + ... \beta_mx_{m,i}}_{deterministic}
\]</span></p></li>
<li class="fragment"><p><span class="math display">\[
y_i \sim \underbrace{N(mean=E[y_i], var=\sigma^2)}_{stochastic}
\]</span></p></li>
<li class="fragment"><p>Same as:</p></li>
<li class="fragment"><p><span class="math display">\[
y_i = \underbrace{\beta_0 + \beta_1x_{1,i} + ... \beta_mx_{m,i}}_{deterministic} \ + \underbrace{\epsilon}_{stachastic}
\]</span></p></li>
<li class="fragment"><p><span class="math display">\[\epsilon \sim nomral(0,\sigma) \]</span></p></li>
</ul>
</section>
<section id="linear-model" class="slide level2">
<h2>linear model</h2>

<img data-src="GLM_Poisson2_files/figure-revealjs/unnamed-chunk-27-1.png" width="960" class="r-stretch"><p><span class="math display">\[ \underbrace{E[y_i]}_{\text{expected value}} = \underbrace{\beta_0 + \beta_1x_{1,i} + ... \beta_mx_{m,i}}_{deterministic} \]</span></p>
<p><span class="math display">\[ y_i \sim \underbrace{N(mean=E[y_i], var=\sigma^2)}_{stochastic} \]</span></p>
</section>
<section id="stochastic-portion-of-a-model" class="slide level2">
<h2>Stochastic portion of a model</h2>
<p>When we talk about the stochastic portion of a model:</p>
<ul>
<li class="fragment"><span class="math display">\[
y_i \sim \underbrace{\beta_0 + \beta_1x_{1,i} + ... \beta_mx_{m,i}}_{deterministic} \ + \underbrace{\epsilon}_{stochastic}
\]</span></li>
<li class="fragment">What is introducing the variance?</li>
<li class="fragment">Is the variance (or observation error) independent?</li>
<li class="fragment">It is unexplained variance!</li>
<li class="fragment">🎣 🦃 🐁🧑‍🏭</li>
<li class="fragment">Is the variance unexplained?</li>
</ul>
</section>
<section id="mixed-model" class="slide level2">
<h2>Mixed model</h2>
<p>Think… how do we introduce that variance?</p>
<p><span class="math display">\[
y_i \sim \underbrace{\beta_0 + \beta_1x_{1,i} + ... \beta_mx_{m,i}}_{deterministic} \ + \underbrace{\epsilon}_{stachastic}
\]</span></p>
<ul>
<li class="fragment"><p>Think for a moment on this specific question: 🐟</p></li>
<li class="fragment"><p><span class="math display">\[
y_i \sim \underbrace{\beta_0 + \beta_1x_{1,i}}_{deterministic} + \underbrace{\epsilon}_{stachastic}
\]</span></p></li>
<li class="fragment"><p><span class="math display">\[
Hg_i \sim \underbrace{\beta_0 + \beta_1size_{i}}_{deterministic} + \underbrace{\epsilon}_{stachastic}
\]</span></p></li>
<li class="fragment"><p><span class="math display">\[ \epsilon \sim N(0,\sigma)\]</span></p></li>
</ul>

<img data-src="GLM_Poisson2_files/figure-revealjs/unnamed-chunk-28-1.png" width="960" class="r-stretch"></section>
<section id="the-variance-can-affect-the-slope-the-intercept-or-both" class="slide level2">
<h2>The variance can affect the slope, the intercept, or both</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="GLM_Poisson2_files/figure-revealjs/unnamed-chunk-29-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<p>What is the problem with this? We can actually do a linear model</p>
<ul>
<li class="fragment"><strong>But remember!</strong> there might be some effect of the locations where nets were placed</li>
</ul>
</div></div>
</section>
<section id="plotting-the-data-as-a-linear-model" class="slide level2">
<h2>Plotting the data as a linear model</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="GLM_Poisson2_files/figure-revealjs/unnamed-chunk-30-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<ul>
<li class="fragment">You might think this is all good… but</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="GLM_Poisson2_files/figure-revealjs/unnamed-chunk-31-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<ul>
<li class="fragment"><p>So… we do a <strong>mixed model!</strong> Where we introduce the variance from the site</p></li>
<li class="fragment"><p>But… why don’t we simply add site as a covariate?</p></li>
<li class="fragment"><p>You will be tasked with answering this on your next assignment!</p></li>
</ul>
</section>
<section id="the-variance-can-affect-the-slope-the-intercept-or-both-1" class="slide level2">
<h2>The variance can affect the slope, the intercept, or both</h2>
<ul>
<li class="fragment"><p>Random effects introduce variance.</p></li>
<li class="fragment"><p>It can introduce varianceto the intercept or to the slope</p></li>
</ul>

<img data-src="GLM_Poisson2_files/figure-revealjs/unnamed-chunk-32-1.png" width="960" class="r-stretch"></section>
<section id="mixed-model-1" class="slide level2">
<h2>Mixed model</h2>
<ul>
<li class="fragment"><p><span class="math display">\[
Hg_i \sim \beta_0 + \beta_1size_{i} + \epsilon
\]</span></p></li>
<li class="fragment"><p>i individuals, j sites (4)</p></li>
<li class="fragment"><p><span class="math display">\[
Hg_i \sim \underbrace{(\beta_0 +\underbrace{\gamma_j}_{\text{Random intercept}})}_{intercept} + \underbrace{\beta_1size_{i}}_{slope} +\underbrace{\epsilon}_\text{ind var}
\]</span></p></li>
<li class="fragment"><p>Variance comes from random “selection” of fish within a net</p></li>
<li class="fragment"><p>Variance comes from random “selection” of sites</p></li>
</ul>
</section>
<section id="mixed-model-2" class="slide level2">
<h2>Mixed model</h2>
<p>This is the result of a mixed model:</p>

<img data-src="GLM_Poisson2_files/figure-revealjs/unnamed-chunk-33-1.png" width="960" class="r-stretch"></section>
<section id="mixed-effects-model-output" class="slide level2">
<h2>Mixed effects model output</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> Family: gaussian  ( identity )
Formula:          Hg ~ size + (1 | region)
Data: HgDat_df

     AIC      BIC   logLik deviance df.resid 
  -147.6   -138.0     77.8   -155.6       76 

Random effects:

Conditional model:
 Groups   Name        Variance Std.Dev.
 region   (Intercept) 0.070287 0.26512 
 Residual             0.006395 0.07997 
Number of obs: 80, groups:  region, 4

Dispersion estimate for gaussian family (sigma^2): 0.0064 

Conditional model:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) 0.5160480  0.1364710   3.781 0.000156 ***
size        0.0197595  0.0008332  23.714  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>

<img data-src="GLM_Poisson2_files/figure-revealjs/unnamed-chunk-35-1.png" width="960" class="r-stretch"></section>
<section id="output" class="slide level2">
<h2>Output</h2>


<img data-src="GLM_Poisson2_files/figure-revealjs/unnamed-chunk-36-1.png" width="960" class="r-stretch"></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="GLM_Poisson2_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="GLM_Poisson2_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="GLM_Poisson2_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="GLM_Poisson2_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="GLM_Poisson2_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="GLM_Poisson2_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="GLM_Poisson2_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="GLM_Poisson2_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="GLM_Poisson2_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="GLM_Poisson2_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="GLM_Poisson2_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>